### ISSUE TITLE
spawn npm ENOENT error

### ISSUE THREAD

**Issue by TheXby** [igniteram/Cliptor.js#34]
Hello,
when using cliptor config there is error and package.json is not changed:
Installing dev dependencies...
{ Error: spawn npm ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn npm',
  path: 'npm',
  spawnargs:
   [ 'i',
     '--loglevel=error',
     '-D',
     'protractor',
     'typescript',
     '@types/node',
     '@types/jasmine',
     'ts-node',
     'eslint',
     'eslint-plugin-protractor' ] }

latest 

Configuration file was created successfully!
To run your tests, execute:
$ protractor protractor.conf.js

**Comment by TheXby** [comment]
i have found how to resolve the issue:
need to add "shell: true" to all spawn('npm'.......

**Comment by igniteram** [comment]
@TheXby It's been a while for me to look at this repo, I am sure dependencies had some breaking changes. Good that you found the solution, If you could send a PR I would be more than happy to review it and merge it to the project. Also I am looking for a maintainer for this repo If you are interested let me know I would add you to the project :innocent:
